#!/usr/bin/env node
var debug = require('debug')('AuthSample');
var app = require('./app.js');

app.set('port', process.env.PORT || 3000);

var server = app.listen(app.get('port'), function() {
  console.log('start at port:' + server.address().port);
  debug('Express server listening on port ' + server.address().port);
});
